### ISSUE TITLE
ZeroDivisionError when running without channels

### ISSUE THREAD

**Issue by openoms** [prusnak/suez#16]
Running wiht a new lnd node without channels:

`poetry run ./suez`

```
Traceback (most recent call last):
  File "./suez", line 5, in <module>
    suez()
  File "/home/bitcoin/.cache/pypoetry/virtualenvs/suez-wt8MvQVn-py3.7/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/bitcoin/.cache/pypoetry/virtualenvs/suez-wt8MvQVn-py3.7/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/bitcoin/.cache/pypoetry/virtualenvs/suez-wt8MvQVn-py3.7/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bitcoin/.cache/pypoetry/virtualenvs/suez-wt8MvQVn-py3.7/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/bitcoin/suez/suez.py", line 155, in suez
    "{}".format(sum(local_base_fees) // len(local_base_fees)),
ZeroDivisionError: integer division or modulo by zero
```

Checking for channels can be handled externally, but a friendlier error message would be nice.

**Comment by prusnak** [comment]
Fixed in 75fa9e6f83b1584965ccb7d24f68ba31d4200a64
